use {
    crate::{
        Labels,
        names, //
    },
    decay_build_ir::Graph,
    decay_meson_logic::{
        Var,
        VarKind, //
    },
    eyre::Context,
    std::{
        fmt::Write as _,
        fs,
        path::Path, //
    },
};

/// The name of the constraint standing for "this configuration cannot exist".
const UNSATISFIABLE: &str = "unsatisfiable";

/// Constraints that belong to meson rather than to any one project.
///
/// Meson's own options, the compiler in use, what the host machine is, whether
/// a header or a library is there — none of that is a property of the project
/// being imported, and two projects that both ask about it are asking the same
/// question. Declaring them once means one platform can answer for every
/// imported project instead of each one inventing its own knob.
#[derive(Debug)]
pub struct Shared {
    /// Build-file path of the package holding these constraints.
    package: String,
    vars: Vec<Var>,
    /// Constraint name for each variable, keyed the way the executor keys them.
    names: std::collections::BTreeMap<String, String>,
}

impl Shared {
    /// Gather the shared constraints across every project being imported.
    pub fn collect<'a>(
        package: String,
        graphs: impl IntoIterator<Item = &'a Graph>,
    ) -> Self {
        let mut vars: Vec<Var> = Vec::new();
        for graph in graphs {
            for var in &graph.options {
                if !is_shared(var) {
                    continue;
                }
                // The same question asked by two projects is one constraint.
                if vars.iter().any(|seen| seen.key == var.key) {
                    continue;
                }
                vars.push(var.clone());
            }
        }

        let names = names::assign_by_key(&vars);
        Self {
            package,
            vars,
            names,
        }
    }

    /// The label selecting one value of a shared variable.
    pub(crate) fn label(&self, var: &Var, value: &str) -> Option<String> {
        let name = self.names.get(&var.key)?;
        Some(format!("//{}:{name}[{value}]", self.package))
    }

    /// Whether this variable is declared here rather than by a project.
    pub(crate) fn owns(&self, var: &Var) -> bool {
        self.names.contains_key(&var.key)
    }

    /// The label of a value no platform sets, used to mark a target that must
    /// not exist in a given configuration.
    pub(crate) fn impossible(&self) -> String {
        format!("//{}:{UNSATISFIABLE}[yes]", self.package)
    }

    pub fn write(&self, known: &Labels, out: &Path) -> eyre::Result<()> {
        fs::create_dir_all(out)
            .wrap_err("Failed to create the shared constraints directory")?;
        fs::write(out.join("BUCK"), self.render(known))
            .wrap_err("Failed to write the shared constraints build file")
    }

    fn render(&self, known: &Labels) -> String {
        let mut out = String::from(
            "# Generated by decay. Do not edit.\n\
             #\n\
             # Constraints that come from meson itself rather than from any one\n\
             # project: meson's own build options, the toolchain, the machine\n\
             # being built for, and what the build environment provides. Every\n\
             # imported project selects on these, so they are declared once.\n",
        );

        let _ = write!(
            out,
            "\n# A value no platform sets. A target that requires it exists in no\n\
             # configuration, which is how a conditional target is expressed.\n\
             constraint(\n    \
             name = {UNSATISFIABLE:?},\n    \
             values = [\"yes\", \"no\"],\n    \
             default = \"no\",\n    \
             visibility = [\"PUBLIC\"],\n)\n"
        );

        for var in &self.vars {
            // A choice the importer was told how to select needs no constraint
            // of its own.
            if known.is_external(var) {
                continue;
            }
            let name = self.names.get(&var.key).expect("every variable was named");
            out.push_str(&crate::render_constraint(var, name));
        }

        out
    }
}

/// Whether a variable is meson's rather than the project's.
fn is_shared(var: &Var) -> bool {
    match var.kind {
        // Only the options a project declares itself are its own: two projects
        // may each declare `tests` and mean unrelated things.
        VarKind::Option => false,
        VarKind::BuiltinOption | VarKind::Machine | VarKind::Probe | VarKind::Dependency => true,
    }
}
