use {
    crate::{
        Labels,
        render_flags_rule, //
    },
    decay_build_ir::{
        External,
        Graph,
        Kind, //
    },
    eyre::Context,
    std::{
        collections::BTreeMap,
        fs,
        path::Path, //
    },
};

/// What the toolchain provides rather than any one project: `find_library()`
/// results and meson's builtin `threads`/`iconv`/`intl` dependencies.
///
/// `-lm` means the same thing to every project that links it, so each is
/// declared once in a package every project depends on, not copied into each
/// project that asks for it.
#[derive(Debug)]
pub struct System {
    rules: BTreeMap<String, External>,
}

impl System {
    /// Gather every system library some imported project actually links.
    pub fn collect<'a>(known: &Labels, graphs: impl IntoIterator<Item = &'a Graph>) -> Self {
        let mut rules = BTreeMap::new();
        for graph in graphs {
            for target in &graph.targets {
                if target.cond.is_false() || known.dependencies.contains_key(&target.label) {
                    continue;
                }
                let Kind::External(external) = &target.kind else {
                    continue;
                };
                if let Some(name) = name(external) {
                    rules.entry(name).or_insert_with(|| external.clone());
                }
            }
        }
        Self { rules }
    }

    /// Write the package, or nothing at all when no project links any.
    pub fn write(&self, out: &Path) -> eyre::Result<()> {
        if self.rules.is_empty() {
            return Ok(());
        }
        fs::create_dir_all(out).wrap_err("Failed to create the system libraries directory")?;
        fs::write(out.join("BUCK"), self.render())
            .wrap_err("Failed to write the system libraries build file")
    }

    fn render(&self) -> String {
        let mut out = String::from(
            "# Generated by decay. Do not edit.\n\
             #\n\
             # Libraries the toolchain provides rather than any one project:\n\
             # `find_library()` results and meson's builtin `threads`, `iconv`\n\
             # and `intl`. Every imported project links the same ones, so they\n\
             # are declared once.\n",
        );
        for (name, external) in &self.rules {
            out.push('\n');
            render_flags_rule(&mut out, name, external);
        }
        out
    }
}

/// The rule name a system library goes by in the shared package, or `None`
/// for an external that is not one. A `find_library()` result is named after
/// the library (`m`, `dl`), unless that would collide with a builtin
/// dependency's own name (`find_library('iconv')` is `libiconv`, not the
/// `dependency('iconv')` builtin).
pub(crate) fn name(external: &External) -> Option<String> {
    match external {
        External::Threads => Some("threads".to_owned()),
        External::Iconv => Some("iconv".to_owned()),
        External::Intl => Some("intl".to_owned()),
        External::SystemLibrary { name }
            if matches!(name.as_str(), "threads" | "iconv" | "intl") =>
        {
            Some(format!("lib{name}"))
        }
        External::SystemLibrary { name } => Some(name.clone()),
        External::Framework { .. } | External::PkgConfig { .. } | External::Program { .. } => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lib(name: &str) -> External {
        External::SystemLibrary {
            name: name.to_owned(),
        }
    }

    #[test]
    fn a_library_is_named_after_itself_unless_a_builtin_has_that_name() {
        assert_eq!(name(&lib("m")).as_deref(), Some("m"));
        assert_eq!(name(&External::Iconv).as_deref(), Some("iconv"));
        assert_eq!(name(&lib("iconv")).as_deref(), Some("libiconv"));
        assert_eq!(
            name(&External::PkgConfig {
                module: "x".to_owned()
            }),
            None
        );
    }

    #[test]
    fn each_library_is_declared_once() {
        let mut graphs = Vec::new();
        for _ in 0..2 {
            let mut graph = Graph::new();
            graph.add(
                "m",
                Path::new(""),
                decay_meson_logic::Pc::TRUE,
                Kind::External(lib("m")),
            );
            graphs.push(graph);
        }
        let text = System::collect(&Labels::default(), &graphs).render();
        assert_eq!(text.matches("name = \"m\"").count(), 1, "{text}");
        assert!(text.contains("\"-lm\""), "{text}");
    }
}
