//! Whether a symbol is part of glibc or musl, on `linux`, for any of
//! [`Cpu::ALL`], without hand-curating a list of function names.
//!
//! `has_function('dlvsym')` and the like otherwise have to become an open
//! configuration knob, because the importer cannot run the compiler. For a
//! symbol glibc itself exports, the answer is knowable without running
//! anything: `data/glibc-abilists` is copied verbatim from a pinned zig
//! release (see `data/PROVENANCE.md`) — the same data glibc's own project
//! publishes, and the data zig uses to synthesize glibc stubs for
//! cross-linking. This module parses that file directly; nothing here is a
//! hand-typed symbol list, and refreshing it means copying in a newer
//! release's copy, never editing one.
//!
//! musl publishes no equivalent list — it has no symbol versioning, so zig
//! just compiles it from source per target rather than shipping a
//! stub-generation database for it. `build.rs` instead asks a real `zig cc`
//! at decay's own build time, for every architecture: which functions
//! musl's own headers declare, and which of those actually link — see its
//! own doc comment. The result is baked into `musl_symbols` below; nothing
//! here is hand-typed for musl either, and none of it comes from glibc's
//! data.
//!
//! The binary format below mirrors `loadMetaData` and the function-inclusion
//! loop in zig's own `src/libs/glibc.zig`.

mod cpu;

pub use cpu::Cpu;

use std::{
    collections::{HashMap, HashSet},
    sync::OnceLock, //
};

/// The vendored `abilists` file. See `data/PROVENANCE.md`.
static ABILISTS: &[u8] = include_bytes!("../data/glibc-abilists");

// Generated by `build.rs`: `musl_symbols(cpu)`, one sorted `&[&str]` per
// `Cpu`, of every candidate name a real `zig cc` link resolved for that arch.
include!(concat!(env!("OUT_DIR"), "/musl_symbols.rs"));

/// Which libc [`has_function`] answers for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Libc {
    Glibc,
    Musl,
}

fn glibc_symbols() -> &'static HashMap<Cpu, HashSet<&'static str>> {
    static TABLE: OnceLock<HashMap<Cpu, HashSet<&'static str>>> = OnceLock::new();
    TABLE.get_or_init(|| {
        Cpu::ALL
            .into_iter()
            .map(|cpu| {
                let symbols = parse(ABILISTS, cpu.zig_arch(), "linux", cpu.glibc_abi())
                    .unwrap_or_else(|| {
                        panic!(
                            "crates/decay_libc_db/data/glibc-abilists is malformed, or has no \
                             {}-linux-{} column",
                            cpu.zig_arch(),
                            cpu.glibc_abi()
                        )
                    });
                (cpu, symbols)
            })
            .collect()
    })
}

/// Whether `name` is a function symbol `libc` exports on `linux`, for `cpu`.
///
/// `false` only means "not found in this database" — it says nothing about
/// any other libc, and a caller must not treat it as proof the symbol does
/// not exist anywhere.
pub fn has_function(libc: Libc, cpu: Cpu, name: &str) -> bool {
    match libc {
        Libc::Glibc => glibc_symbols()
            .get(&cpu)
            .is_some_and(|set| set.contains(name)),
        Libc::Musl => musl_symbols(cpu).binary_search(&name).is_ok(),
    }
}

/// Reads a NUL-terminated string starting at `*idx`, advancing past the NUL.
fn read_cstr(data: &'static [u8], idx: &mut usize) -> Option<&'static str> {
    let start = *idx;
    let end = start + data[start..].iter().position(|&b| b == 0)?;
    *idx = end + 1;
    std::str::from_utf8(&data[start..end]).ok()
}

/// Reads a ULEB128-encoded `u64` starting at `*idx`.
fn read_uleb128_u64(data: &[u8], idx: &mut usize) -> Option<u64> {
    let mut result: u64 = 0;
    let mut shift = 0u32;
    loop {
        let byte = *data.get(*idx)?;
        *idx += 1;
        result |= u64::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return Some(result);
        }
        shift += 7;
    }
}

/// Parses the vendored abilist into the set of function symbol names present
/// for the `<arch>-<os>-<abi>` triple (e.g. `x86_64`, `linux`, `gnu`).
///
/// Format, verbatim from zig's `loadMetaData` (the header) and the
/// function-inclusion loop in `buildSharedObjects` (the body):
///
/// ```text
/// u8               lib count
/// (cstr)*          that many library names ("m", "pthread", "c", ...)
/// u8               version count
/// (u8 u8 u8)*      that many (major, minor, patch) triples
/// u8               target count
/// (cstr)*          that many "<arch>-linux-<abi>" triples
/// u16 (LE)         function-inclusion count
/// inclusion*       that many function inclusions (below)
/// u16 (LE)         object-inclusion count (data symbols; not parsed here)
/// ```
///
/// An inclusion is one (symbol name, targets, library, versions) fact; a
/// symbol with entries in more than one library or target list appears as
/// several consecutive inclusions that share one name, the last one marked
/// terminal:
///
/// ```text
/// (cstr)?          the symbol name, only when the previous inclusion for
///                  this symbol was not terminal (i.e. omitted otherwise)
/// uleb128          bitset of which target index this inclusion covers
/// u8               library index; high bit set means this is the last
///                  inclusion for this symbol name
/// ver+             one byte per version this inclusion holds for; high bit
///                  set on the last one
/// ```
fn parse(data: &'static [u8], arch: &str, os: &str, abi: &str) -> Option<HashSet<&'static str>> {
    let mut idx = 0usize;

    let n_libs = *data.get(idx)? as usize;
    idx += 1;
    for _ in 0..n_libs {
        read_cstr(data, &mut idx)?;
    }

    let n_versions = *data.get(idx)? as usize;
    idx += 1;
    idx += n_versions * 3;

    let n_targets = *data.get(idx)? as usize;
    idx += 1;
    let mut target_index = None;
    for i in 0..n_targets {
        let triple = read_cstr(data, &mut idx)?;
        let mut parts = triple.split('-');
        let (t_arch, t_os, t_abi) = (parts.next()?, parts.next()?, parts.next()?);
        if t_os == os && t_arch == arch && t_abi == abi {
            target_index = Some(i);
        }
    }
    let target_index = target_index? as u32;

    let mut present = HashSet::new();

    let fn_inclusions_len = u16::from_le_bytes([*data.get(idx)?, *data.get(idx + 1)?]) as usize;
    idx += 2;

    let mut pending_name: Option<&'static str> = None;
    for _ in 0..fn_inclusions_len {
        let name = match pending_name {
            Some(name) => name,
            None => read_cstr(data, &mut idx)?,
        };

        let targets = read_uleb128_u64(data, &mut idx)?;
        let lib_byte = *data.get(idx)?;
        idx += 1;
        pending_name = if lib_byte & 0x80 != 0 {
            None
        } else {
            Some(name)
        };

        if targets & (1u64 << target_index) != 0 {
            present.insert(name);
        }

        // The version-index run for this inclusion; its content does not
        // matter here, only walking past it to reach the next inclusion.
        loop {
            let byte = *data.get(idx)?;
            idx += 1;
            if byte & 0x80 != 0 {
                break;
            }
        }
    }

    Some(present)
}

#[cfg(test)]
mod tests {
    use super::{Cpu, Libc, has_function};

    #[test]
    fn finds_a_gnu_extension_on_every_arch() {
        // A GNU extension no other libc ships, and the motivating example
        // for this database (see `example/decay.toml`'s hand-written
        // `has_function:dlvsym` entry, which this makes automatic).
        for cpu in Cpu::ALL {
            assert!(has_function(Libc::Glibc, cpu, "dlvsym"), "{cpu:?}");
            assert!(!has_function(Libc::Musl, cpu, "dlvsym"), "{cpu:?}");
        }
    }

    #[test]
    fn finds_plain_libc_on_every_arch() {
        for cpu in Cpu::ALL {
            for name in ["malloc", "strlen", "printf"] {
                assert!(
                    has_function(Libc::Glibc, cpu, name),
                    "glibc {cpu:?}: {name}"
                );
                assert!(has_function(Libc::Musl, cpu, name), "musl {cpu:?}: {name}");
            }
        }
    }

    #[test]
    fn finds_a_musl_capable_extension() {
        // Declared and implemented by musl, not by glibc's abilist for
        // whatever glibc version this was pinned against.
        assert!(has_function(Libc::Musl, Cpu::X86_64, "explicit_bzero"));
    }

    #[test]
    fn does_not_find_nonsense() {
        for cpu in Cpu::ALL {
            assert!(!has_function(
                Libc::Glibc,
                cpu,
                "this_is_not_a_real_libc_symbol"
            ));
            assert!(!has_function(
                Libc::Musl,
                cpu,
                "this_is_not_a_real_libc_symbol"
            ));
        }
    }

    #[test]
    fn does_not_find_a_static_inline_only_declaration() {
        // Declared in musl's headers but implemented as `static __inline`
        // (byteswap.h) — no linkable symbol, so this must stay absent even
        // though step 1 of build.rs's musl pass sees the declaration.
        assert!(!has_function(Libc::Musl, Cpu::X86_64, "__bswap_32"));
    }

    #[test]
    fn finds_an_x86_only_musl_function_on_x86_but_not_arm() {
        // x86 I/O-port privilege syscalls: declared in musl's headers on
        // every arch, but only ever linkable on x86(_64) — the motivating
        // example for probing every arch separately rather than reusing one
        // arch's answer everywhere.
        assert!(has_function(Libc::Musl, Cpu::X86_64, "ioperm"));
        assert!(!has_function(Libc::Musl, Cpu::Arm64, "ioperm"));
    }
}
